### ISSUE TITLE
Provide update script

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/scripts#4]
Can we provide an ubuntu-upgrade.sh script?

Scope is:

1. Update the Nginx / PHP / extensions / everything to a later version if it is available and that new version is supported by FreeScout.
2. Advise if the version of Ubuntu is outdated
3. Advise if any other maintenance needs to be performed on this server

# Why

Because the install instructions for freescout are so simple on a clean ubuntu server, I see that many people with no sysadmin experience are installing freescout. Great!

This also means they will never upgrade PHP. Boo!

By having this script, we can recommend people to use it before they create a bug report. And we will be able to reduce the variety of PHP versions and other platform versions we are supporting. This will make it easier to support the software.

**Comment by freescout-helpdesk** [comment]
All FreeScout scripts now will be stored in the main repo: https://github.com/freescout-helpdesk/freescout/tree/dist/tools
Please comment there.
